name: Bug 报告
description: 提交一个问题，帮助我们复现与修复
labels: [bug]
title: "[Bug] "
body:
  - type: input
    id: page
    attributes:
      label: 影响页面
      description: 填写受影响的页面路径或链接
      placeholder: 例如 /feeding.html
  - type: textarea
    id: repro
    attributes:
      label: 复现步骤
      description: 按步骤描述如何复现
      placeholder: |
        1) 打开…
        2) 输入…
        3) 点击…
        4) 看到…
    validations:
      required: true
  - type: input
    id: expected
    attributes:
      label: 期望行为
      placeholder: 你希望看到的结果
  - type: textarea
    id: actual
    attributes:
      label: 实际行为/截图
      description: 可粘贴文字、图片或错误信息
  - type: dropdown
    id: env
    attributes:
      label: 环境
      options: [Desktop, Mobile]
  - type: input
    id: browser
    attributes:
      label: 浏览器/版本（可选）
      placeholder: 例如 Chrome 128 / Edge 127
