name: Link Check
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          # 说明：
          # --exclude-mail    跳过邮箱链接
          # --exclude-file    读取根目录的 .lycheeignore
          # 最后的 "." 表示检查整个仓库
          args: >
            --verbose
            --no-progress
            --timeout 20s
            --max-concurrency 8
            --exclude-mail
            --exclude-file .lycheeignore
            .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
