name: Link Check
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --timeout 20s --max-concurrency 8 --exclude-mail ./ -a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
